### ISSUE TITLE
Green lights not lighting despite passing all tests

### ISSUE THREAD

**Issue by jellybeanjohnny** [learn-co-curriculum/swift-extensions-lab#1]
All tests passed in Xcode but the lights on Learn do not reflect this. 
<img width="771" alt="screen shot 2016-07-13 at 5 25 54 pm" src="https://cloud.githubusercontent.com/assets/6811982/16820425/ee16ef66-491e-11e6-90a9-2f1ddd8a8634.png">

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.
