### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by pressstart101** [learn-co-curriculum/swift-extensions-lab#2]
tests didnt work for me

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by AnnJohn** [comment]
hi @pressstart101 can you be a bit more explicit about what happened with the tests not working for you? thanks

**Comment by pressstart101** [comment]
hard to remember, it was 1,5 months ago
